"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/header/Header'
import { relative } from 'path'
import SideBar from '../components/sidebar/SideBar'
import { useRouter } from 'next/navigation';
import mainPage from '../store/mainPage'; 
import { Providers } from './provider'
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const router = useRouter()

  return (
    <html lang="en">
      <body /*className={inter.className}*/>
        <main >
          <div >
          </div>
          <div>
              <Providers>{children}</Providers>
          </div>
        </main>
      </body>
    </html>
  )
}
