import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/header/Header'
import { relative } from 'path'
import SideBar from '../components/sidebar/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main style={{ display: 'flex', justifyContent: 'flex-start', alignItems: 'center' }}>
          <div style={{marginRight: '20px'}}>
            <SideBar />
          </div>
          <div>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
